kubernetes:
  base:
    repoName: checkout-ui-tests
    repoOrg: vtex
    imageRepository: 558830342743.dkr.ecr.us-east-1.amazonaws.com
    environment: stable
    secretsManager:
      enabled: true
      secretsName: stable/checkout-ui-tests/checkout-ui-tests
    version: latest
  apps:
  - name: checkout-tests-cronjob
    kind: cronjob
    schedule: "* * * * *"
    activeDeadlineSeconds: 10800 # 3 hours
    startingDeadlineSeconds: 6000
    envs:
    - name: VTEX_ENV
      value: stable
    - name: HORUS_COGNITO_CREDENTIALS
      valueFrom:
        secretKeyRef:
          name: checkout-ui-tests
          key: HORUS_COGNITO_CREDENTIALS
          optional: false
    - name: CYPRESS_APP_KEY
      valueFrom:
        secretKeyRef:
          name: checkout-ui-tests
          key: APP_KEY
          optional: false
    - name: CYPRESS_APP_TOKEN
      valueFrom:
        secretKeyRef:
          name: checkout-ui-tests
          key: APP_TOKEN
          optional: false
    dockerfile: ./dockerfiles/stable/Dockerfile
    imageRepoName: healthcheck/webtests/checkout
    imagePullPolicy: Always
    command: ["yarn", "test"]
    volumes:
    - name: dshm
      mountPath: /dev/shm
    serviceAccount:
      arn: arn:aws:iam::558830342743:role/s3-healthcheck-io
    resources:
      requests:
        cpu: 2
        memory: 2Gi
      limits:
        cpu: 2
        memory: 2Gi
  - name: checkout-io-tests-cronjob
    kind: cronjob
    schedule: "* * * * *"
    activeDeadlineSeconds: 10800 # 3 hours
    startingDeadlineSeconds: 6000
    envs:
    - name: VTEX_ENV
      value: io
    - name: HORUS_COGNITO_CREDENTIALS
      valueFrom:
        secretKeyRef:
          name: checkout-ui-tests
          key: HORUS_COGNITO_CREDENTIALS
          optional: false
    - name: CYPRESS_APP_KEY
      valueFrom:
        secretKeyRef:
          name: checkout-ui-tests
          key: APP_KEY
          optional: false
    - name: CYPRESS_APP_TOKEN
      valueFrom:
        secretKeyRef:
          name: checkout-ui-tests
          key: APP_TOKEN
          optional: false
    dockerfile: ./dockerfiles/stable/Dockerfile
    imageRepoName: healthcheck/webtests/checkout
    imagePullPolicy: Always
    command: ["yarn", "test"]
    volumes:
    - name: dshm
      mountPath: /dev/shm
    serviceAccount:
      arn: arn:aws:iam::558830342743:role/s3-healthcheck-io
    resources:
      requests:
        cpu: 2
        memory: 2Gi
      limits:
        cpu: 2
        memory: 2Gi
